// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.crm.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LineItemDataOnDemand_Roo_Configurable {
    
    declare @type: LineItemDataOnDemand: @Configurable;
    
}
