// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.crm.domain;

import com.malsolo.crm.domain.LineItemDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LineItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LineItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LineItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: LineItemIntegrationTest: @Transactional;
    
    @Autowired
    private LineItemDataOnDemand LineItemIntegrationTest.dod;
    
    @Test
    public void LineItemIntegrationTest.testCountLineItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to initialize correctly", dod.getRandomLineItem());
        long count = com.malsolo.crm.domain.LineItem.countLineItems();
        org.junit.Assert.assertTrue("Counter for 'LineItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LineItemIntegrationTest.testFindLineItem() {
        com.malsolo.crm.domain.LineItem obj = dod.getRandomLineItem();
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getLineItemId();
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to provide an identifier", id);
        obj = com.malsolo.crm.domain.LineItem.findLineItem(id);
        org.junit.Assert.assertNotNull("Find method for 'LineItem' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'LineItem' returned the incorrect identifier", id, obj.getLineItemId());
    }
    
    @Test
    public void LineItemIntegrationTest.testFindAllLineItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to initialize correctly", dod.getRandomLineItem());
        long count = com.malsolo.crm.domain.LineItem.countLineItems();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'LineItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.malsolo.crm.domain.LineItem> result = com.malsolo.crm.domain.LineItem.findAllLineItems();
        org.junit.Assert.assertNotNull("Find all method for 'LineItem' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'LineItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LineItemIntegrationTest.testFindLineItemEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to initialize correctly", dod.getRandomLineItem());
        long count = com.malsolo.crm.domain.LineItem.countLineItems();
        if (count > 20) count = 20;
        java.util.List<com.malsolo.crm.domain.LineItem> result = com.malsolo.crm.domain.LineItem.findLineItemEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'LineItem' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'LineItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LineItemIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to initialize correctly", dod.getRandomLineItem());
        com.malsolo.crm.domain.LineItem obj = dod.getNewTransientLineItem(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'LineItem' identifier to be null", obj.getLineItemId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'LineItem' identifier to no longer be null", obj.getLineItemId());
    }
    
    @Test
    public void LineItemIntegrationTest.testRemove() {
        com.malsolo.crm.domain.LineItem obj = dod.getRandomLineItem();
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getLineItemId();
        org.junit.Assert.assertNotNull("Data on demand for 'LineItem' failed to provide an identifier", id);
        obj = com.malsolo.crm.domain.LineItem.findLineItem(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'LineItem' with identifier '" + id + "'", com.malsolo.crm.domain.LineItem.findLineItem(id));
    }
    
}
