// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.malsolo.crm.domain;

import com.malsolo.crm.domain.CartOrder;
import com.malsolo.crm.domain.CartOrderDataOnDemand;
import com.malsolo.crm.domain.LineItem;
import com.malsolo.crm.domain.Product;
import com.malsolo.crm.domain.ProductDataOnDemand;
import java.lang.Long;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LineItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LineItemDataOnDemand: @Component;
    
    private Random LineItemDataOnDemand.rnd = new SecureRandom();
    
    private List<LineItem> LineItemDataOnDemand.data;
    
    @Autowired
    private CartOrderDataOnDemand LineItemDataOnDemand.cartOrderDataOnDemand;
    
    @Autowired
    private ProductDataOnDemand LineItemDataOnDemand.productDataOnDemand;
    
    public LineItem LineItemDataOnDemand.getNewTransientLineItem(int index) {
        LineItem obj = new LineItem();
        setCartOrderId(obj, index);
        setProductId(obj, index);
        setQuantity(obj, index);
        return obj;
    }
    
    public void LineItemDataOnDemand.setCartOrderId(LineItem obj, int index) {
        CartOrder cartOrderId = cartOrderDataOnDemand.getRandomCartOrder();
        obj.setCartOrderId(cartOrderId);
    }
    
    public void LineItemDataOnDemand.setProductId(LineItem obj, int index) {
        Product productId = productDataOnDemand.getRandomProduct();
        obj.setProductId(productId);
    }
    
    public void LineItemDataOnDemand.setQuantity(LineItem obj, int index) {
        Long quantity = new Integer(index).longValue();
        obj.setQuantity(quantity);
    }
    
    public LineItem LineItemDataOnDemand.getSpecificLineItem(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        LineItem obj = data.get(index);
        return LineItem.findLineItem(obj.getLineItemId());
    }
    
    public LineItem LineItemDataOnDemand.getRandomLineItem() {
        init();
        LineItem obj = data.get(rnd.nextInt(data.size()));
        return LineItem.findLineItem(obj.getLineItemId());
    }
    
    public boolean LineItemDataOnDemand.modifyLineItem(LineItem obj) {
        return false;
    }
    
    public void LineItemDataOnDemand.init() {
        data = LineItem.findLineItemEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'LineItem' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.malsolo.crm.domain.LineItem>();
        for (int i = 0; i < 10; i++) {
            LineItem obj = getNewTransientLineItem(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
